language: python
python:
  - "2.7"
"before_install": [
  "python -m pip install --upgrade setuptools pip virtualenv"
]
# command to install dependencies
install: [
  "sudo apt-get install python-opencv",
  "pip install -e ."
]
# command to run tests
script: pytest
